language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
    - composer self-update
    - ./tests/travis/apc.sh
    # Install APC via beta
    #- sh -c "if [[ $TRAVIS_PHP_VERSION != 'hhvm' && `php-config --vernum` -ge 50500 ]] ; then pecl config-set preferred_state beta; yes "" | pecl install apcu ;fi"
    # Set PHP.ini file location
    #- sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-add ./tests/travis/php.ini; fi"